# Generated by Django 5.0.6 on 2024-05-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='locailzacao',
            new_name='localizacao',
        ),
    ]
